version: "3.8"
services:
  site-db:
    container_name: site-db-${IMAGE_TAG}
    build:
      context: ./site-db
    shm_size: 4gb 
    volumes:
      - type: bind
        source: ./site-db/docker-volume
        target: /var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
  redismod:
    container_name: redismod-${IMAGE_TAG}
    build:
      context: ./redismod
    entrypoint: "/usr/local/bin/redis-server"
    command: "--include /usr/local/etc/redis/redis.conf --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisearch.so"
    volumes:
      - type: bind
        source: ./redismod/redis.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
    ports:
      - 6379:6379
  
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - 9090:9090

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   restart: unless-stopped
  #   links:
  #     - prometheus:prometheus
  #   volumes:
  #     - ./data/grafana:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=12345
  #   ports:
  #     - 3001:3000

  # retool:
  #   image: tryretool/backend:latest
  #   restart: unless-stopped
  #   environment:
  #     - LICENSE_KEY=${RETOOL_LICENSE_KEY}
  #     - COOKIE_INSECURE=true
  #   ports:
  #     - 3002:3000
  #     - 3003:3001
  #     - 3004:3002