version: "3.8"
services:
  site-db:
    container_name: site-db-${IMAGE_TAG}
    image: memehub/site-db:${IMAGE_TAG}
    build:
      context: ./site-db
    shm_size: 4gb 
    volumes:
      - type: bind
        source: ./site-db/backups
        target: /backups
      - type: bind
        source: ./site-db/docker-volume
        target: /var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
  redismod:
    container_name: redismod-${IMAGE_TAG}
    image: memehub/redismod:${IMAGE_TAG}
    build:
      context: ./redismod
    entrypoint: "/usr/local/bin/redis-server"
    command: "--include /usr/local/etc/redis/redis.conf --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisearch.so"
    volumes:
      - type: bind
        source: ./redismod/redis.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
    ports:
      - 6379:6379